<script lang="ts">
	import { token } from '../stores';

	let loading: boolean = false;

	let username: string;
	let password: string;

	async function login(e: SubmitEvent) {
		e.preventDefault();
		loading = true;

		const formData = new FormData();

		formData.append('username', username);
		formData.append('password', password);

		const response = await fetch('http://localhost:3000/api/auth/login', {
			method: 'POST',
			body: formData,
		});

		if (response.ok) {
			return token.set(await response.text());
		}

		console.log(response);

		loading = false;
	}
</script>

<form
	class="max-w-screen-sm mx-auto flex justify-center flex-col h-screen p-16 gap-5"
	method="POST"
	autocomplete="new-password"
	on:submit={login}
>
	<h1 class="text-3xl font-bold mb-3 underline">Login</h1>

	<fieldset class="">
		<label for="username" class="block mb-2 text-sm font-medium text-gray-900 "
			>Username</label
		>
		<input
			type="text"
			id="username"
			class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 "
			placeholder="John Doe"
			required
			autocomplete="new-password"
			bind:value={username}
		/>
	</fieldset>

	<fieldset class="">
		<label for="password" class="block mb-2 text-sm font-medium text-gray-900 "
			>Password</label
		>
		<input
			type="password"
			id="password"
			class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 "
			placeholder="******************"
			required
			autocomplete="new-password"
			bind:value={password}
		/>
	</fieldset>

	<button
		type="submit"
		class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center mt-5"
	>
		{#if loading}
			<svg
				xmlns="http://www.w3.org/2000/svg"
				xmlns:xlink="http://www.w3.org/1999/xlink"
				style="margin: auto; background: none; display: block; shape-rendering: auto;"
				width="25px"
				height="25px"
				viewBox="0 0 100 100"
				preserveAspectRatio="xMidYMid"
			>
				<circle
					class="stroke-slate-50"
					cx="50"
					cy="50"
					fill="none"
					stroke="#b0b0b0"
					stroke-width="10"
					r="35"
					stroke-dasharray="164.93361431346415 56.97787143782138"
				>
					<animateTransform
						attributeName="transform"
						type="rotate"
						repeatCount="indefinite"
						dur="1s"
						values="0 50 50;360 50 50"
						keyTimes="0;1"
					/>
				</circle>
				<!-- [ldio] generated by https://loading.io/ --></svg
			>
		{:else}
			<span>submit</span>
		{/if}
	</button>
</form>
